# Generated by Django 4.2.1 on 2023-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCity', models.IntegerField()),
                ('nameCity', models.CharField(max_length=50)),
                ('descriptionCity', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='cars')),
                ('assetCity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCity', models.IntegerField()),
                ('idCustomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCountry', models.IntegerField()),
                ('nameCountry', models.CharField(max_length=50)),
                ('descriptionCountry', models.CharField(max_length=200)),
                ('assetCountry', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCustomer', models.IntegerField()),
                ('nameCustomer', models.CharField(max_length=50)),
                ('assetCustomer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaymentMethods', models.IntegerField()),
                ('namePaymentMethods', models.CharField(max_length=50)),
                ('assetPaymentMethods', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaymentMethods', models.IntegerField()),
                ('idCustomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRole', models.IntegerField()),
                ('nameRole', models.CharField(max_length=50)),
                ('assetRole', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSeller', models.IntegerField()),
                ('nameSeller', models.CharField(max_length=50)),
                ('assetSeller', models.BooleanField()),
            ],
        ),
    ]
