# Generated by Django 4.2.1 on 2023-06-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo',
            name='idEjemplo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejemplo',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
