# Generated by Django 4.2.1 on 2023-06-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='idCountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.country'),
            preserve_default=False,
        ),
    ]
