# Generated by Django 4.2.1 on 2023-06-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_city_idcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='idCountry',
        ),
    ]
