# Generated by Django 4.2.1 on 2023-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ciudad_ciudadescliente_cliente_formas_de_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCity', models.IntegerField()),
                ('nameCity', models.CharField(max_length=50)),
                ('descriptionCity', models.CharField(max_length=200)),
                ('assetCity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCity', models.IntegerField()),
                ('idCustomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCountry', models.IntegerField()),
                ('nameCountry', models.CharField(max_length=50)),
                ('descriptionCountry', models.CharField(max_length=200)),
                ('assetCountry', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCustomer', models.IntegerField()),
                ('nameCustomer', models.CharField(max_length=50)),
                ('assetCustomer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaymentMethods', models.IntegerField()),
                ('namePaymentMethods', models.CharField(max_length=50)),
                ('assetPaymentMethods', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaymentMethods', models.IntegerField()),
                ('idCustomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRole', models.IntegerField()),
                ('nameRole', models.CharField(max_length=50)),
                ('assetRole', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSeller', models.IntegerField()),
                ('nameSeller', models.CharField(max_length=50)),
                ('assetSeller', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='ciudadesCliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Ejemplo',
        ),
        migrations.DeleteModel(
            name='Formas_de_Pago',
        ),
        migrations.DeleteModel(
            name='Formas_de_pago_de_Cliente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
