# Generated by Django 4.2.1 on 2023-06-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_city_city_customer_country_customer_paymentmethods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(default=0, upload_to='cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
