# Generated by Django 4.2.1 on 2023-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_city_photo_city_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
