# Generated by Django 4.2.1 on 2023-06-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_city_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
    ]
