# Generated by Django 4.2.1 on 2023-06-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
