# Generated by Django 4.2.1 on 2023-06-09 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(default=datetime.date.today, upload_to='photo'),
            preserve_default=False,
        ),
    ]
