# Generated by Django 4.2.1 on 2023-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
