# Generated by Django 4.2.1 on 2023-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='descriptionCity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='nameCity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nameCustomer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='namePaymentMethods',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='nameRole',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nameSeller',
            field=models.CharField(max_length=255),
        ),
    ]
