# Generated by Django 4.2.1 on 2023-06-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_city_descriptioncity_alter_city_namecity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
    ]
